### ISSUE TITLE
libraft fails to compile using JDK 7

### ISSUE THREAD

**Issue by allengeorge** [allengeorge/libraft#32]
Builds on JDK 1.7.0_45 fail with:

"MockDriver.java:59: error: MockDriver is not abstract and does not override abstract method getParentLogger() in Driver"

**Comment by allengeorge** [comment]
I have decided to drop support for JDK 6 and move to JDK 7.
